import datetime
from typing import Any, Optional, Protocol

from app.projects.c13200175.domain.models.file import File
from app.projects.c13200175.domain.models.geo_event import GeoEvent


class IRefreshTokenRepository(Protocol):
    async def create(self, token: str, user_id: str, email: str, expires_at: datetime.datetime, device_id: Optional[str]) -> None: ...
    async def find(self, token: str) -> Optional[dict[str, Any]]: ...
    async def delete(self, token: str) -> None: ...


class IUserRepository(Protocol):
    async def find_by_email(self, email: str) -> Optional[dict[str, Any]]: ...
    async def find_by_google_id(self, google_id: str) -> Optional[dict[str, Any]]: ...
    async def create_user(self, user: dict[str, Any]): ...


class IGoogleOAuthClient(Protocol):
    async def verify_id_token(self, id_token: str) -> dict | None: ...


class IGeoEventRepository(Protocol):
    async def create(self, data: dict[str, Any]) -> GeoEvent: ...
    async def find_by_id(self, id: int) -> Optional[GeoEvent]: ...
    async def find_all(self, user_id: Optional[str], event_type: Optional[str], limit: int, offset: int) -> list[GeoEvent]: ...
    async def delete(self, id: int) -> bool: ...


class IFileRepository(Protocol):
    async def create(self, data: dict[str, Any]) -> File: ...
    async def find_by_id(self, id: int) -> Optional[File]: ...
    async def find_by_project_and_user(self, project_slug: str, user_id: str, limit: int, offset: int) -> list[File]: ...
    async def delete(self, id: int) -> bool: ...


class IStorageClient(Protocol):
    async def get_upload_url(self, key: str, content_type: str, expires_in: int) -> str: ...
    async def delete(self, key: str) -> None: ...
    async def get_url(self, key: str, expires_in: int) -> str: ...
