from typing import Any, Optional, Protocol

from app.projects.layout_example.domain.models.geo_event import GeoEvent


class IUserRepository(Protocol):
    async def find_by_email(self, email: str) -> Optional[dict[str, Any]]: ...
    async def find_by_google_id(self, google_id: str) -> Optional[dict[str, Any]]: ...
    async def create_user(self, user: dict[str, Any]): ...


class IGoogleOAuthClient(Protocol):
    async def verify_id_token(self, id_token: str) -> dict | None: ...


class IGeoEventRepository(Protocol):
    async def create(self, data: dict[str, Any]) -> GeoEvent: ...
    async def find_by_id(self, id: int) -> Optional[GeoEvent]: ...
    async def find_all(self, user_id: Optional[str], event_type: Optional[str], limit: int, offset: int) -> list[GeoEvent]: ...
    async def delete(self, id: int) -> bool: ...
