from typing import Any, Optional, Protocol


class IUserRepository(Protocol):
    async def find_by_email(self, email: str) -> Optional[dict[str, Any]]: ...
    async def find_by_google_id(self, google_id: str) -> Optional[dict[str, Any]]: ...
    async def create_user(self, user: dict[str, Any]): ...


class IGoogleOAuthClient(Protocol):
    async def verify_id_token(self, id_token: str) -> dict | None: ...
